# Header
menu:
  返回狗窝: /
  所有文章: /archives
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: bottom
widgets:
- category
- tag

# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
